# Generated by Django 5.0.6 on 2024-07-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_topbar_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbar_db',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
