# Generated by Django 5.0.6 on 2024-07-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_topbar_db_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='service_card_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.TextField()),
                ('card_description', models.TextField()),
                ('card_img', models.ImageField(default=' ', upload_to='media/card_img')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
